version: '3.5'
networks:
  ignite-dds_kafka-net:
    external:
      name: ignite-dds_kafka-net
services:
  postgres:
    image: postgres:latest
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - 5433
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5433:5433"
    restart: unless-stopped
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/api
    volumes:
      - media-attachments:${MEDIA_ATTACHMENTS_DIRECTORY}
    env_file:
      - .env
    ports:
    - ${IGNITE_API_PORT}:${IGNITE_API_PORT}
    depends_on:
      - postgres
    networks:
      - default
      - ignite-dds_kafka-net
  sia-synchornizer:
    build:
      context: ./sia-synchronizer
      dockerfile: Dockerfile
    working_dir: /var/www/api
    volumes:
    - media-attachments:${MEDIA_ATTACHMENTS_DIRECTORY}
    env_file:
      - .env
    ports:
      - 7777:7777
    depends_on:
      - postgres
    networks:
      - default
volumes:
  pg-data:
    external:
      name: ${PGDATA_EXTERNAL_VOLUME}
  media-attachments:
    external:
      name: ${MEDIA_ATTACHMENTS_VOLUME}
